### ISSUE TITLE
pep8 compliance

### ISSUE THREAD

**Issue by vanadium23** [gi0baro/weppy#102]
There is a good practice to follow [pep8](https://www.python.org/dev/peps/pep-0008/) rules for lib projects. I have suggestion to add [pyflakes](https://pypi.python.org/pypi/pyflakes) to travil builds and refactor code according to it.

Is there any negative points for that improvement?

**Comment by gi0baro** [comment]
@vanadium23 yep, I don't have pyflakes runs on travis, but I use integrated pep8 linting in my editor, so the actual code should be pep8 compliant ~99% :)
If you want to push a PR for that I will accept it.

**Comment by vanadium23** [comment]
Hope doesn't break too much (:

**Comment by vanadium23** [comment]
Was done in #105
