### ISSUE TITLE
NameError: name 'has_many' is not defined

### ISSUE THREAD

**Issue by aachik** [gi0baro/weppy#106]
OS: windows 10
python version: activepython 2.7.10

Following the tutorial: http://weppy.org/docs/0.6/tutorial

after running:
`weppy --app bloggy.py run`

The following is shown:

> PS C:\Users\AbdulHamid\Documents\weppy\bloggy> weppy --app bloggy.py run
> Traceback (most recent call last):
>   File "C:\Python27\Scripts\weppy-script.py", line 9, in <module>
>     load_entry_point('weppy==0.6.2', 'console_scripts', 'weppy')()
>   File "C:\Python27\lib\site-packages\weppy\cli.py", line 358, in main
>     cli.main(args=args, prog_name=name)
>   File "C:\Python27\lib\site-packages\weppy\cli.py", line 209, in main
>     return click.Group.main(self, *args, **kwargs)
>   File "C:\Python27\lib\site-packages\click\core.py", line 696, in main
>     rv = self.invoke(ctx)
>   File "C:\Python27\lib\site-packages\click\core.py", line 1060, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "C:\Python27\lib\site-packages\click\core.py", line 889, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "C:\Python27\lib\site-packages\click\core.py", line 534, in invoke
>     return callback(*args, **kwargs)
>   File "C:\Python27\lib\site-packages\click\decorators.py", line 64, in new_func
>     return ctx.invoke(f, obj, *args[1:], **kwargs)
>   File "C:\Python27\lib\site-packages\click\core.py", line 534, in invoke
>     return callback(*args, **kwargs)
>   File "C:\Python27\lib\site-packages\weppy\cli.py", line 222, in run_command
>     app = info.load_app()
>   File "C:\Python27\lib\site-packages\weppy\cli.py", line 136, in load_app
>     a = locate_app(self.app_import_path)
>   File "C:\Python27\lib\site-packages\weppy\cli.py", line 98, in locate_app
>     module, mod, app_obj = get_app_module(app_id)
>   File "C:\Python27\lib\site-packages\weppy\cli.py", line 91, in get_app_module
>     __import__(module)
>   File "C:\Users\AbdulHamid\Documents\weppy\bloggy\bloggy.py", line 4, in <module>
>     from models import *
>   File "C:\Users\AbdulHamid\Documents\weppy\bloggy\models.py", line 5, in <module>
>     class User(AuthUser):
>   File "C:\Users\AbdulHamid\Documents\weppy\bloggy\models.py", line 7, in User
>     has_many('posts', 'comments')
> NameError: name 'has_many' is not defined

code: https://github.com/aachik/bloggy-weppy/blob/master/bloggy.py#L10

Maybe i did something wrong, anyway im loving your framework so far so much

**Comment by lethargilistic** [comment]
That is an error in the docs. The import for `has_many` is missing.

To get you going for now, `has_many` comes from `weppy.dal` and you can also see a full implementation of [bloggy in the repo](https://github.com/gi0baro/weppy/blob/master/examples/bloggy/bloggy.py#L2).

**Comment by gi0baro** [comment]
@aachik as @lethargilistic said, just add to your models file:

```python
from weppy.dal import belongs_to, has_many
```

I'm sorry for the inconvenient.

@lethargilistic thank you for the catch.

**Comment by gi0baro** [comment]
I'm closing this since fixed with #107, dev docs will be updated consequentially, while 0.6 docs will be updated on the next bugfix release.
