### ISSUE TITLE
Why I can't use `url("static", "img/favicon.ico")` function in my haml file

### ISSUE THREAD

**Issue by laozhu** [gi0baro/weppy#116]
I want to include some static files in my haml file and use url function like this:

```haml
%meta{name: 'msapplication-TileImage', content: 'url("static", "img/favicon.png")'}
%link{rel: 'icon', sizes: '192x192', href: 'url("static", "img/favicon.png")'}
%link{rel: 'apple-touch-icon', sizes: '192x192', href: 'url("static", "img/favicon.png")'}
%link{rel: 'shortcut icon', type: 'image/x-icon', href: 'url("static", "img/favicon.ico")'}
- include_static 'bs3/bootstrap.min.css'
```

The last line can load static file correctly, others failed. If I should load sth in my haml header to use url function? Maybe there's other method I don't know to make it, I think the docs about [The url() function](http://weppy.org/docs/0.6/routing#the-url-function) or [Include helpers](http://weppy.org/docs/0.6/templates#included-helpers) docs lacks some details.

I need some help :)

**Comment by cassiobotaro** [comment]
The correct is 
```haml
%meta{name: 'msapplication-TileImage', content: '{{=url("static", "img/favicon.png")}}'}
%link{rel: 'icon', sizes: '192x192', href: '{{=url("static", "img/favicon.png")}}'}
```

**Comment by gi0baro** [comment]
@laozhu yes, @cassiobotaro is right, the `url` function is python powered, so you still have to use the weppy template decorators `{{ }}` to use it inside the template, both with html and haml.

**Comment by laozhu** [comment]
@cassiobotaro Maybe I am still in Django template style, thanks for your help :+1: 
@gi0baro I think in [The url() function](http://weppy.org/docs/0.6/routing#the-url-function) section should include something about url usage in template, it will be helpful to someone like me migrate from django template or jinja2.

**Comment by gi0baro** [comment]
@laozhu have you read the templating chapter? In particular http://weppy.org/docs/0.6/templates#included-helpers and http://weppy.org/docs/0.6/templates#basic-context sections? Maybe I should better describe the usage of `url` in those sections?

**Comment by laozhu** [comment]
Actually, I read the two section more than 3 times :)

I am not familiar with pure python code in template, this is why I can't get `{{=url('static', 'js/app.js')}}` usage by myself; I am familiar with Django or Flask url function in template, so I write it like this: `url('static', 'js/app.js')`.

I think [The templating system](http://weppy.org/docs/0.6/templates) needs better describe for how to include static files (except css and js) in template and how to include route name in template.

And when you show us how writing python in template powerful, this could be a nice example :)

**Comment by gi0baro** [comment]
Ok, I've created #117
