### ISSUE TITLE
Mailer refactoring

### ISSUE THREAD

**Issue by gi0baro** [gi0baro/weppy#135]

**Comment by AzureusNation** [comment]
What needs to be done on this? Can i help in any way?

**Comment by gi0baro** [comment]
Hi @AzureusNation, the idea was to drop the current code in [mail.py](https://github.com/gi0baro/weppy/blob/master/weppy/tools/mail.py), since is a port of really-old code; it should work on python3 but I never wrote accurate tests.

This is my idea of what should be done:
- rewrite the module from scratch, maybe looking at [flask-mail](https://github.com/mattupstate/flask-mail)
- write tests (the mailer should support also a contextmanager to don't really send messages)
- write the documentation

If you want to help with anything you're welcome :)

**Comment by AzureusNation** [comment]
@gi0baro Doesn't the auth hook into the mail.py at the moment? Would it be the case where the Auth would also be a module?

**Comment by gi0baro** [comment]
@AzureusNation nope, the auth module just use an instance of the mailer right now. And this will be the case even after the module refactoring, so no worries about the auth :)

**Comment by AzureusNation** [comment]
So this is what i have come up with so far. Nothing is set in stone but essentially i've taken my knowlage from Java and Kotlin and mad Message a builder to make it as simple as possible.

Essentially you would do the following:

```python
mail = Mail
message = mail.new_message.set_to('anyone@theworld.com').set_subject('test').set_body('hello world!')
mail.send_mail(message)
```

So in 3 lines your sending an email. You could make it 2 lines:

```python
mail = Mail
mail.send_mail(mail.new_message.set_to('anyone@theworld.com').set_subject('test').set_body('hello world!'))
```

Another addition i want to add is alternates so one for html and one for plain text. I also want to add attachments but what for you think? Any changes that are needed?

```python

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from weppy.extensions import Extension


class Mail(Extension):
    default_config = dict(
        mail_server='127.0.0.1',
        mail_port=25,
        mail_from_addr='',
        mail_username='',
        mail_password='',
        mail_use_tls=False,
        mail_use_ssl=False,
    )

    def on_load(self):
        self._load_config()

    def _load_config(self):
        self.config.mail_server = self.config.get('mail_server', self.default_config['mail_server'])
        self.config.mail_port = self.config.get('mail_port', self.default_config['mail_port'])
        self.config.mail_from_addr = self.config.get('mail_from_addr', self.default_config['mail_from_addr'])
        self.config.mail_username = self.config.get('mail_username', self.default_config['mail_username'])
        self.config.mail_password = self.config.get('mail_password', self.default_config['mail_password'])
        self.config.mail_use_tls = self.config.get('mail_use_tls', self.default_config['mail_use_tls'])
        self.config.mail_use_ssl = self.config.get('mail_use_ssl', self.default_config['mail_use_ssl'])

    def _connection(self):
        if self.config.mail_use_ssl:
            server = smtplib.SMTP_SSL(self.config.mail_server, self.config.mail_port,
                                      source_address=self.config.mail_from_addr)
        else:
            server = smtplib.SMTP(self.config.mail_server, self.config.mail_port,
                                  source_address=self.config.mail_from_addr)
        if self.config.mail_use_tls:
            server.starttls()
        return server

    def new_message(self):
        return Message(self.config.mail_from_addr)

    def send_mail(self, message):
        server = self._connection()
        if self.config.mail_username and self.config.mail_password:
            server.login(self.config.mail_username, self.config.mail_password)
        server.send_message(message)
        server.close()


class Message:

    def __init__(self, from_address):
        self.message = MIMEMultipart()
        self.message['From'] = from_address

    def set_to(self, to):
        self.message['To'] = to
        return self

    def set_cc(self, cc):
        self.message['Cc'] = cc
        return self

    def set_bcc(self, bcc):
        self.message['Bcc'] = bcc
        return self

    def set_subject(self, subject):
        self.message['Subject'] = subject
        return self

    def set_body(self, body):
        self.message.attach(MIMEText(body))
        return self
```

**Comment by gi0baro** [comment]
@AzureusNation thank you. Here are my considerations:

- it looks quite java-ish, in fact would be more pythonic using the mailer like this: `mail.send_mail(to='anyone@theworld.com', subject='test', body='hello world!')`
- yes we need attachments since the actual system supports them

**Comment by Marlysson** [comment]
You want drop all code or refactor them ?

**Comment by gi0baro** [comment]
@Marlysson the idea is to refactor all the code, I don't know yet if this will mean to drop everything and restart from scratch. I'm actually working on #134, will update this when I'll start.

**Comment by Marlysson** [comment]
Great , OK then :+1:
