### ISSUE TITLE
Option to enforce SSL

### ISSUE THREAD

**Issue by GiantCrocodile** [gi0baro/weppy#137]
I suggest that we have an option to enforce site-wide SSL/https.

**Comment by gi0baro** [comment]
@GiantCrocodile I need more context about this.
Should be enforced with a variable of the router? Let's say:

```python
app.route.https_only = True
```

Should be enforced on the debugging server?

I usually enforce it on the webserver in production..

**Comment by GiantCrocodile** [comment]
I will close this now as I don't think it is relevant anymore.
