### ISSUE TITLE
Url function return bad urls if parameters in route are splitted by char different than /

### ISSUE THREAD

**Issue by hydeparkk** [gi0baro/weppy#140]
If I have a route defined like this:

``` python
@app.route('/post/<int:post_id>(\.<str:post_title>)?')
def post(post_id, post_title):
    pass
```

And then call an url function in template:

``` python
url('post', (12,))  # returns '/post/12'
url('post', (12, 'sample-post-title')) # returns '/post/12/sample-post-title'
                                       # should be '/post/12.sample-post-title'
```

it works like a charm only when the first parameter is passed to the url function, passing two or more parameters result with an url that does not match route.

**Comment by gi0baro** [comment]
@hydeparkk this is probably because I've never thought about something like this. Interesting :)
I'm gonna check this out.

**Comment by gi0baro** [comment]
I'm moving this to 1.0 since refactoring of the router is scheduled with #136
