### ISSUE TITLE
Custom forms

### ISSUE THREAD

**Issue by josejachuf** [gi0baro/weppy#148]
I was trying to use custom form as does web2py [1].

```
{{=form.custom.begin}}
Name: <div>{{=form.custom.widget.name}}</div>
File: <div>{{=form.custom.widget.source}}</div>
{{=form.custom.submit}}
{{=form.custom.end}}
```

Apparently it works well, except that does not maintain the **class style**.

```
form = MyModel.form()
form.add_class('pure-form')
```

If the view use: {{= form}} I get:
`<form action="" class="pure-form" enctype="multipart/form-data" method="POST">`

however if you use custom form, I get:
```
<form action="" enctype="multipart/form-data" method="POST">
</form>
```
Jose

[1] http://web2py.com/books/default/chapter/29/07/forms-and-validators#Custom-forms

**Comment by gi0baro** [comment]
Yes form.custom actually doesn't consider other *attributes* rather than action, enctype and method. Will update this behavior.

**Comment by josejachuf** [comment]
@gi0baro This work fine:
[weppy/forms.py line 185]
```
begin = '<form action="%s" method="%s" enctype="%s" class="%s">' % \
            (self.attributes['_action'],
             self.attributes['_method'],
             self.attributes['_enctype'],
             self.attributes['_class']
             )
```
There may be to make it extensive to other attributes.
The button submit does not maintain its attributes
Jose
