### ISSUE TITLE
multiple route and one function  work random，404

### ISSUE THREAD

**Issue by alingse** [gi0baro/weppy#153]
Here is my simple app  server,use two route `/api/v1/book/isbn/<str:isbn>` and `/api/v1/book/<int:bookid>`

when I visit `http://127.0.0.1:8001/api/v1/book/isbn/1231`
It works 50% work at `#return 1` ，50% 404，
I dont know why，It has run inside the book function already。

This is my code：

``` python
#coding=utf-8
from weppy import request
from weppy import App
from weppy.tools import service

app = App(__name__)

import random

@app.route('/api/v1/book/isbn/<str:isbn>')
@app.route('/api/v1/book/<int:bookid>')
@service.json
def book(isbn=None,bookid=None):

    if random.random()>0.5:
    #return 1
        return isbn
    #return 2
    if isbn != None:
        data = {'isbn':isbn}
    if bookid != None:
        bookid = int(bookid)
        data = {'id':bookid}

    return data

if __name__ == '__main__':
    app.debug = True
    app.run(host='0.0.0.0', port=8001)
```

**Comment by gi0baro** [comment]
Hi @alingse, I'm sorry but right now multiple route decorations are not supported.
This is already on issues (see https://github.com/gi0baro/weppy/issues/108) but have no ETA.

The current weppy wants you to write something like this (is ugly, I know):

```python
def book(isbn=None,bookid=None):
    # code returning data

@app.route('/api/v1/book/isbn/<str:isbn>')
@service.json
def book_wisbn(isbn):
    return book(isbn=isbn)

@app.route('/api/v1/book/<int:bookid>')
@service.json
def book_wid(bookid):
    return book(bookid=bookid)
```

**Comment by hydeparkk** [comment]
Hi @gi0baro, I've done little research and it looks like multiple route decorations works fine, but the problem here is with *@service.json* decorator.
I've created pull request (#155) with changes to make this work properly.

**Comment by alingse** [comment]
Hi @gi0baro , I have just test the package post by @hydeparkk ,his weppy  works well.

and I do some test on latest weppy(0.7.8)
```python
....
@app.route('/api/v1/book/isbn/<str:isbn>')
@app.route('/api/v1/book/<int:bookid>')
#@service.json
def book(isbn=None,bookid=None):
    if True:
        return str([bookid,isbn])
...
```
It also works well,
http://127.0.0.1:8001/api/v1/book/isbn/1231 --> `[None, '1231']`
http://127.0.0.1:8001/api/v1/book/123123  --> `['123123', None]`

I try say more thing about my first code
```python
    if random.random()>0.5:
    #return 1
        return isbn
    #return 2
    ....
    return data
```
just go into `return 1` is always works,but when go into `return 2`,It became `404`.

I think something wrong while `@service.json` visit and return the args `isbn`or `id`in function `book`.

**Comment by gi0baro** [comment]
@alingse please use the code I given to test your code.

**Comment by alingse** [comment]
Yes, @gi0baro ,  
I test the code you given, It works well.

And Inspired by your code and the comment
I find it might need twice `@service.json` for every route 

```python
@app.route('/api/v1/book/isbn/<str:isbn>')
@service.json
@app.route('/api/v1/book/<int:bookid>')
@service.json
def book(isbn=None,bookid=None):
    return [isbn,bookid]
```
It works too, It seems because  the python‘s  decorator order , but I still know nothing.
Thank you && Thank @hydeparkk too.

**Comment by gi0baro** [comment]
@alingse thank you for sharing your experiments. Will keep this open until complete support for multiple routes is implemented so I can update you about the status. There's no official ETA, but probably will be included in weppy 1.0, scheduled for the end of the year/start of the next year.

**Comment by gi0baro** [comment]
@alingse I have an update on this.
Since 6d1845c (master pre 1.0) the route decorator allow to use multiple paths.
Your example should now be written:

```python
@app.route(['/api/v1/book/isbn/<str:isbn>', '/api/v1/book/<int:bookid>'])
@service.json
def book(isbn=None,bookid=None):
    # code
```

When you need to build reverse routing with the `url` helper, the first route is always applied:

```python
>>> url('book', 'fe23')
/api/v1/book/isbn/fe23
```

if you need anyone of the other paths, you can use an underscore notation with the position in the array:

```python
>>> url('book_1', 123)
/api/v1/book/123
```

@alingse I would love to hear your feedback on this. If you are satisfied with the solution, I'm gonna close this and update the docs for the 1.0

**Comment by alingse** [comment]
##  nice ,  this can be closed

`Route` class is much better

and `@route` accepts multi paths is also interesting.

yet I have two advice about `url` in [issues 173](https://github.com/gi0baro/weppy/issues/173)

**Comment by gi0baro** [comment]
@alingse ok, I'm closing this.
