### ISSUE TITLE
Allow to mix custom validators with standard syntax

### ISSUE THREAD

**Issue by gi0baro** [gi0baro/weppy#158]
eg:

``` python
validation = {
    'field_name': {'is': 'int', 'custom': my_method}
}
```

**Comment by Marlysson** [comment]
What is need to this task are done?

**Comment by gi0baro** [comment]
@Marlysson add the parsing and addition of the custom validator here: https://github.com/gi0baro/weppy/blob/master/weppy/validators/__init__.py#L104

Mind that probably this should probably inserted before the *allow* parsing, see line https://github.com/gi0baro/weppy/blob/master/weppy/validators/__init__.py#L244 or the order will probably break.

**Comment by Marlysson** [comment]
@gi0baro excellent .. I will see and analysing the weppy source code and your workflow .. some doubts I will come back here..

**Comment by gi0baro** [comment]
@Marlysson sure, thank you!

**Comment by Marlysson** [comment]
@gi0baro 
This feature looks like this?

http://weppy.org/docs/0.8/validations

Section **Custom Validator**

**Comment by gi0baro** [comment]
@Marlysson yep, see the description

**Comment by Marlysson** [comment]
Then this already done?

**Comment by gi0baro** [comment]
@Marlysson nope.
Right now you can use the weppy validation language (eg: `{'is': 'int', 'gte': 0, 'lt': 6}` or a custom validator of your own.

The issue is to use both of them, as reported in the description. 
So the validation parser (https://github.com/gi0baro/weppy/blob/master/weppy/validators/__init__.py#L104#L250) should be updated to add a validator specified with the `'custom'` key into the final list of operations.
