### ISSUE TITLE
Update record not update rowattr

### ISSUE THREAD

**Issue by josejachuf** [gi0baro/weppy#180]
@gi0baro 
In reference to this thread [1]. When a row is updated it is not reflected in the rowattr
I imagine that behavior is inherited from pyDAL

[1] https://groups.google.com/forum/#!topic/weppy-talk/oZVE71hVXuw

**Comment by josejachuf** [comment]
In web2py has the same behavior

**Comment by josejachuf** [comment]
@gi0baro 

rowmethod solve this?
Yes, at least for me

**Comment by gi0baro** [comment]
@josejachuf yes `rowattr` is an attribute so it won't be updated if is dependant on other attributes of the row. You should use `rowmethod` for that.
