### ISSUE TITLE
remember_option is ignored

### ISSUE THREAD

**Issue by josejachuf** [gi0baro/weppy#183]
Hi @gi0baro 

[weppy 1.0]

setting 

`app.config.auth.remember_option = False`

Does not work, is ignored and is always True

**Comment by josejachuf** [comment]
@gi0baro , You're right, that's the problem. I had considered it, but as I saw other settings worked, I discarded putting it before the declaration of auth.

**Comment by gi0baro** [comment]
@josejachuf Nice. Just remember: in weppy you have to write the configuration just after you initialized the app. `Database`, `Auth`, `Mailer`, all extensions read the configuration when you initialize them, and won't be sensible to any change made later.
