### ISSUE TITLE
About signed urls

### ISSUE THREAD

**Issue by josejachuf** [gi0baro/weppy#195]
@gi0baro, Based on bloggy, I added signature.py. (Attached)

Modifications to bloggy.py:

`from signature import SignPipe, SignInjector`

`app.injectors = [SignInjector()]`

```
@app.route("/post/<int:pid>", pipeline=[SignPipe()])
def one(pid):
   ...
```
```
@app.route("/new")
@requires(lambda: auth.has_membership('admin'), url('index'))
def new_post():
    form = Post.form()
    if form.accepted:
        redirect(url('one', form.params.id, sign=SignInjector.sign))
    return dict(form=form)

```

index.html
```
{{extend 'layout.html'}}

<a href="{{=url('new_post')}}">Create a new post</a>
<ul class="posts">
{{for post in posts:}}
    <li>
        <h2>{{=post.title}}</h2>
        <a href="{{=url('one', post.id, sign=sign)}}">Read more</a>
        <hr />
    </li>
{{pass}}
{{if not posts:}}
    <li><em>No posts here so far.</em></li>
{{pass}}
</ul>
```

As you can see only the **one** function requires that it be signed.

It happens that after entering a signed link [**"Read more"**] other links are signed, for example **new_post**. It is as if the _signature parameter appears in each url, so when the signature is created, the url already contains another signature and it is obvious that validation will always fail.

I found a solution modifying weppy / espose / url by removing the _signature parameter if it exists in params like this:

```
# add signature
    if '_signature' in params:
        params.pop('_signature')

    if sign:
        params['_signature'] = sign(
            path, args, params, anchor, scheme, host, language)
```
Can you apply this change to the repository?

[bloggy.zip](https://github.com/gi0baro/weppy/files/1047913/bloggy.zip)

**Comment by gi0baro** [comment]
@josejachuf yup, make sense. Will update the master later today.

**Comment by gi0baro** [comment]
@josejachuf this is published in 1.0.7
Please, forgive me for the delay

**Comment by josejachuf** [comment]
@gi0baro A within the if condition, fails. Moving it outside works well.

The following works fine:
    ```
    if '_signature' in params:
            del params['_signature']
    if sign:
        params['_signature'] = sign(
            path, args, params, anchor, scheme, host, language)
```

**Comment by gi0baro** [comment]
@josejachuf how it fails? what do you mean? it doesn't make sense..

**Comment by josejachuf** [comment]
@gi0baro  With fault I mean that the same thing that happened at the beginning of this thread, sign the url containing the signature parameter.
It's true, it does not seem to make sense. In fact, before opening this issues I had tried to modify my sign function, deleting the **_signature** parameter:
```

class SignInjector(Injector):
    @staticmethod
    def sign(path, args, params, anchor, scheme, host, language):
        s = Signer(KEY)
        if '_signature' in params:
            del params['_signature']
        builder = RouteUrl([url(path)])
        _url = builder.url(None, None, language, args, params, None)
        _url = str.encode(_url)
        signature = s.get_signature(_url).decode("utf-8")
        return signature
```
I do not know what's going on inside, but I have the impression that it has to do with recursive calls to the url function. it's possible?

What I can assure is that putting the code that removes the _signature parameter as I did everything works fine
Jose

**Comment by gi0baro** [comment]
@josejachuf yes I imagine it works, but it's actually quite risky for the rest of the world, 'cause it means you can't have a `_signature` parameter in the url independently if you use the signature or not, which is not a behaviour I can push on every weppy user :(

Can you try to log the params in your sign method, so we can understand if it's a recursion problem?

**Comment by josejachuf** [comment]
Help this?

```
class SignInjector(Injector):
    @staticmethod
    def sign(path, args, params, anchor, scheme, host, language):
        app.log.debug('params: %s' % str(params))
        s = Signer(KEY)
        builder = RouteUrl([url(path)])
        _url = builder.url(None, None, language, args, params, None)
        _url = str.encode(_url)
        app.log.debug('url: %s' % _url)
        signature = s.get_signature(_url).decode("utf-8")

        return signature

```        
With:        
   ```
 if sign:
        if '_signature' in params:
            del params['_signature']
        params['_signature'] = sign(
            path, args, params, anchor, scheme, host, language)
```

> > DEBUG in signature [./aplicacion/modules/signature.py:13]:
> params: {'id': 8}
> > DEBUG in signature [./aplicacion/modules/signature.py:19]:
> url: b'/expedientes/ficha?_signature=w7YnJlKzhMU3JvZaFRWVE9i9tbc?id=8'

Two things are shown:
1) In params it is not a _signature key,
2) The url, before the signature, already contains the parameter _signature
 
------------------------------------------------    
 With the following code:   
   ```
 if '_signature' in params:
        del params['_signature']
    if sign:
        params['_signature'] = sign(
            path, args, params, anchor, scheme, host, language)
```
   
url to sign is clean:

> > DEBUG in signature [./aplicacion/modules/signature.py:13]:
> params: {'id': 8}
> > DEBUG in signature [./aplicacion/modules/signature.py:19]:
> url: b'/expedientes/formulario?id=8'

**Comment by gi0baro** [comment]
@josejachuf I think the problem is `path` already contains query params.

Try edit this line in your injector:

```python
builder = RouteUrl([url(path)])
```

to 

```python
builder = RouteUrl([url(path.split("?")[0])])
```

**Comment by josejachuf** [comment]
@gi0baro That works.

**Comment by josejachuf** [comment]
@gi0baro, Sorry, I had written that it worked, but this does not happen. The same problem occurs.

In the log I show the path:
> 
> > DEBUG in signature [./aplicacion/modules/signature.py:13]:
> path: expedientes.ficha
> 
> > DEBUG in signature [./aplicacion/modules/signature.py:14]:
> params: {'id': 1}
> 
> > DEBUG in signature [./aplicacion/modules/signature.py:21]:
> url: b'/expedientes/ficha?_signature=pteH0AWL1qCKrF0BiQgZVYjjksQ/1?id=1'

```
class SignInjector(Injector):
    @staticmethod
    def sign(path, args, params, anchor, scheme, host, language):
        app.log.debug('path: %s' % path)
        app.log.debug('params: %s' % str(params))
        s = Signer(KEY)
        # builder = RouteUrl([url(path)])
        builder = RouteUrl([url(path.split("?")[0])])
        _url = builder.url(None, None, language, args, params, None)
        _url = str.encode(_url)
        app.log.debug('url: %s' % _url)
        signature = s.get_signature(_url).decode("utf-8")
        return signature
```

**Comment by josejachuf** [comment]
@gi0baro, I opted to clean the url by hand before signing it, I opted to clean the url by hand before signing it:

```
class SignInjector(Injector):
    @staticmethod
    def sign(path, args, params, anchor, scheme, host, language):

        app.log.debug('path: %s' % path)
        app.log.debug('params: %s' % str(params))
        s = Signer(KEY)
        builder = RouteUrl([url(path)])        
        _url = builder.url(None, None, language, args, params, None)

        p = _url.find('_signature')
        if p > 0:
            _url = _url[:p-1] + _url[p+38:]

        _url = str.encode(_url)
        app.log.debug('url: %s' % _url)
        signature = s.get_signature(_url).decode("utf-8")

        return signature
```
