### ISSUE TITLE
Missing form widget for field type decimal

### ISSUE THREAD

**Issue by josejachuf** [gi0baro/weppy#200]
RuntimeError: Missing form widget for field my_field of type decimal(18,4)
I tried with this:

```
@staticmethod
def widget_decimal(attr, field, value, _class='float', _id=None):
    return FormStyle.widget_string(attr, field, value, _class, _id)

```
But expects the name of the property to be "widget_decimal(18,4)"

Also with this:
 ```
   form_widgets = {
        'my_field': FormStyle.widget_float
    }

```
TypeError: widget_float() missing 1 required positional argument: 'value'

**Comment by gi0baro** [comment]
@josejachuf yup this is a bug. I should patch the `FormStyle` class. Will keep you updated on this.

**Comment by josejachuf** [comment]
For now I solved it with a custom widget. Thanks
