### ISSUE TITLE
cookie template

### ISSUE THREAD

**Issue by Bronte2k7** [gi0baro/weppy#201]
Hi Giovanni

Please add the option to change cookie template for SessionCookieManager, SessionRedisManager

Thank you

**Comment by gi0baro** [comment]
@Bronte2k7 what do you mean with "template"? I'm not sure I understood your issue correctly.

**Comment by Bronte2k7** [comment]
Excuse me. I meant cookie_data_name

**Comment by gi0baro** [comment]
Got it. I will consider this for the next version.

**Comment by gi0baro** [comment]
@Bronte2k7 this is available in 1.2
