### ISSUE TITLE
Date validator

### ISSUE THREAD

**Issue by josejachuf** [gi0baro/weppy#202]
Given a date field, if I apply the following validation:

`'fecha': {'format': '%d/%m/%Y'}`

It works well. When I edit the record from a Model.form the date is displayed and required in the format indicated.

Now, if the validation is the following:

`'fecha': {'format': '%d/%m/%Y', 'allow': 'empty'},`

In the Model.form, the validation works fine, but the date is displayed in this format: YYYY-MM-DD, which, before submitting, forces me to modify the value to DD/MM/YYYY

**Comment by gi0baro** [comment]
@josejachuf will inspect this shortly
