### ISSUE TITLE
Shell command doesn't work

### ISSUE THREAD

**Issue by kdebowski** [gi0baro/weppy#212]
I'm going through tutorial and bumped into troubles when trying to call command from shell:
`weppy --app bloggy.py setup`

I get response message:
```
Usage: weppy [OPTIONS] COMMAND [ARGS]...

Error: No such command "setup".
```
My bloggy.py file content: https://pastebin.com/9eP3Hqec

**Comment by gi0baro** [comment]
@kdebowski custom commands are loaded from the application module, so, usually, when they don't show up it means there's something wrong with your application.

Probably if you open up a shell, it will show you the error with its traceback:

    weppy --app bloggy.py shell

**Comment by kdebowski** [comment]
@gi0baro thanks! I had some bad indentation. Everything works fine. 
Just to mention there some inconsistency in documentation:
On tutorial page (http://weppy.org/docs/1.2/tutorial) the syntax to run command is:
`> weppy --app bloggy.py setup`
On page (http://weppy.org/docs/1.2/cli) the syntax is:
`> weppy --app=myapp setup`.
As I can see both works.

**Comment by gi0baro** [comment]
@kdebowski there's no difference. But thank you for spotting the difference, I will unify the notation.

I'm closing this, feel free to reopen it if you still have issues.
