### ISSUE TITLE
Example of how to run query for JSON fields?

### ISSUE THREAD

**Issue by gcmurphy** [gi0baro/weppy#215]
I'm not sure if pydal exposes this functionality of databases but I'd be interested in an example (if it is possible) of how to query json fields. 

Something along the lines of [what exists for PonyORM](https://docs.ponyorm.com/json.html).

**Comment by gi0baro** [comment]
Hi @gcmurphy,
currently no, it's not supported unless implementing the operators on your own, an example is available at [this gist](https://gist.github.com/gi0baro/56e5368c219b2ca73c9727fec73be36e).

This will definitely be available in next major version, thanks to ORM rewrite, but currently there's no ETA.

**Comment by gcmurphy** [comment]
Ok thanks. I should be able to work around this in the meantime anyway.
