### ISSUE TITLE
Default value presentation in select widgets and other relation fields

### ISSUE THREAD

**Issue by yevheniidehtiar** [gi0baro/weppy#226]
Hi! It's not good in view, when I see IDs instead names on relation fields in form.
`
class Category(Model):
 
    name = Field()
    iso_code = Field.int()
    can_be_main = Field.bool()

    refers_to({'parent': 'self'})
    has_many({'children': 'self.parent'})
`
Field parent in form is select widget and values looking like with 1,2. But I want to see the name of category. I found 'representation' feature in docs, but example in docs is not fully understandably. Can you help me with it. Please

**Comment by josejachuf** [comment]
Hi @yevheniidehtiar You can see in the documentation

http://www.weppy.org/docs/1.2/validations  -> Inclusion in database sets
I believe that is what you are needed

**Comment by yevheniidehtiar** [comment]
Thank you. And what's about multiple select for many2many fields.
For example, I must to pick many groups to user on User's model form?

**Comment by josejachuf** [comment]
@yevheniidehtiar, I'm not sure, but I think with 'multiple': True it could work

**Comment by gi0baro** [comment]
@yevheniidehtiar you might want to add the `format` attribute to your model:

```python
class Category(Model):
    format = "%(name)s"
```

**Comment by yevheniidehtiar** [comment]
How about multiple select fields for relation.  Can you give example, if it's possible?

**Comment by yevheniidehtiar** [comment]
@gi0baro I understand, but I found `multiple` option in **weppy/forms.py**:
`@staticmethod
    def widget_select(attr, field, value, _class='', _id=None):
        def selected(k):
            return 'selected' if str(value) == str(k) else None

        options, multiple = FormStyle._field_options(field)
        if multiple:
            return FormStyle.widget_multiple(
                attr, field, value, options, _class=_class, _id=_id)
        option_items = [
            tag.option(n, _value=k, _selected=selected(k)) for k, n in options]
        return tag.select(
            *option_items, _name=field.name, _class=_class,
            _id=_id or field.name)

    @staticmethod
    def widget_multiple(attr, field, values, options, _class='', _id=None):
        def selected(k):
            return 'selected' if str(k) in [str(v) for v in values] else None

        values = values or []
        option_items = [
            tag.option(n, _value=k, _selected=selected(k)) for k, n in options]
        return tag.select(
            *option_items, _name=field.name, _class=_class,
            _multiple='multiple', _id=_id or field.name)
`
I tried to use @josejachuf way with **multiple: True** , but it's return error. I hardcore it, but working only widget_select.  
Can you have some example with hand-coded form with many2many widget default **rw** logic?
I think that weppy must to have "ready to go" widgets with customization in model.form_widgets.
For example, to o2m we can choose: 'radiobutton', 'select', 'select_auto` (with autocomplete). To m2m - `multiselect`, `multiselect_auto`. Bootstrap has it.

**Comment by gi0baro** [comment]
@yevheniidehtiar No, multiple is used for list fields.
As of today, weppy forms interacts with the referred model only, which means you can have widgets for `belongs_to` and `refers_to` because those are fields on the model, while `has_many` and `has_one` are relations that involve separated models, not the one you're editing.

I'm sorry, but it's totally unplanned right now to have such functionality in weppy. If you want such functions you should implements all the logics to save related models in the route, and if you manage to do it with some "reusable logic", I'm open to pull requests and further discussions :)
