### ISSUE TITLE
pipeline injector

### ISSUE THREAD

**Issue by josejachuf** [gi0baro/weppy#232]
Hi @gi0baro 
Something changed in version 1.3 that broke all the injectors (in 1.2.11 it works fine)

>  File "/my_path/venv36/lib/python3.6/site-packages/weppy/pipeline.py", line 131, in __init__
>     for attr in set(dir(self)) - self._pipeline_methods_:
> AttributeError: 'MyIjector' object has no attribute '_pipeline_methods_'

**Comment by gi0baro** [comment]
@josejachuf should be fixed with ce11697, can you try latest master?

**Comment by josejachuf** [comment]
@gi0baro works fine
Thanks
