### ISSUE TITLE
Major error reloading Python

### ISSUE THREAD

**Issue by gsaidah** [gi0baro/weppy#27]
When I reloaded Python, I got this message on my screen:

uWSGI Error

Python application not found

And now I cannot access the Rascal anymore.
Can someone help please?

**Comment by gi0baro** [comment]
Can you give me more details about your issue?
weppy version, how you're launching it, how you've implemented it on Rascal..

**Comment by gsaidah** [comment]
Thank you very much for the follow-up,
I got it fixed. I made an error in a procedure that crashed the Rascal.
I was able to log in to the editor and repair my code, then reload Python and it worked great.
Thanks again,
George
