### ISSUE TITLE
serializers.items ... module object has no attribute 'items'. 

### ISSUE THREAD

**Issue by Sashley** [gi0baro/weppy#39]
pydal\base.py line 477. for k, v in self.serializers.items():
There has been some discussion (web2py-users) about an issue in April, but its been throwing this error on the latest version.

**Comment by gi0baro** [comment]
Hi @Sashley, I'm sorry about that. The issue comes from a change in pyDAL's API from v15.05.

So, if you're using weppy 0.3, just install pyDAL 15.03 manually with pip before installing weppy.
0.4 (should be released by the end of the month) will be compliant with latest pyDAL.
