### ISSUE TITLE
bloggy Example not working

### ISSUE THREAD

**Issue by ramstein74** [gi0baro/weppy#53]
its missing this code from bloggy.py 

if __name__ == "__main__":
    app.run()

**Comment by gi0baro** [comment]
@ramstein74 this is true only on windows, since on unix systems the tutorial suggest to use the weppy command:

```
weppy --app bloggy.py run
```

**Comment by gi0baro** [comment]
@ramstein74 actually, also on windows you should have a weppy.exe command installed..
