### ISSUE TITLE
Add support for float as variable rule

### ISSUE THREAD

**Issue by GiantCrocodile** [gi0baro/weppy#55]
I'm reading http://weppy.org/docs/0.5/quickstart#variable-rules and I would like to use no integer but float. Could we see support for this in weppy?

**Comment by gi0baro** [comment]
Hi @GiantCrocodile,
the main deals with a float variable rule are:
1) internationally speaking, there are regions which use the dot notation (2.75) and other regions which use the comma notation (2,75). Rationally speaking, the dot notation should be used (keeping the same logic of the python language), but I'm not so sure everybody will understand it correctly.
2) which precision should be used? I mean a float number can be just 3.14 but also something like 3.1415926535897932384626433832795028841971693993751058209749445923078164... So, which precision should I force for a float number?

Considering this, I'm currently working on different new features and I don't consider this as a priority. Generally speaking as a web developer, when I need to work with float numbers in urls, I find query parameters more safe.

(nice nickname, btw ^^)

**Comment by gi0baro** [comment]
Implemented since aeba096
