### ISSUE TITLE
Example for AuthUserBasic usage needed

### ISSUE THREAD

**Issue by GiantCrocodile** [gi0baro/weppy#59]
I'm sorry for spamming this tracker/repo but I need an example for the usage of AuthUserBasic. Regardless what I try to import or subclass the AuthUserBasic, at the end it is

```
NameError: name 'AuthUserBasic' is not defined
```

@gi0baro are you more happy with stuff like this over here or on StackOverflow? I plan to use this framework for one of my projects productive :).

**Comment by gi0baro** [comment]
@GiantCrocodile no problem :) Maybe you can use the [weppy user group](https://groups.google.com/forum/#!forum/weppy-talk) for questions regarding the development of applications, I'm not sure at the moment I have the time to follow every weppy question on stackoverflow :/

Anyway, I've just tested:
```
(weppytest)➜  Test  python
Python 2.7.8 (default, Nov  6 2014, 14:53:57)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from weppy.tools.auth.models import AuthUserBasic
>>> AuthUserBasic
<class 'weppy.tools.auth.models.AuthUserBasic'>
```

So, seems that information available in [auth chapter of docs](http://weppy.org/docs/0.5/auth#authorization-models) are correct :)
