### ISSUE TITLE
How to write test for my weppy app ?

### ISSUE THREAD

**Issue by toplinuxsir** [gi0baro/weppy#70]
I think this is a wonderfull python web framework ,
But, I can not find how to write test for my webpy app in official document.

**Comment by GiantCrocodile** [comment]
There is nothing official for this in the docs but you can see some tests in test directory of weppy. See this link: https://github.com/gi0baro/weppy/tree/master/tests

Tho I'm not sure if this is real testing you look for or any helpful to you. This is just a hint I may have.

**Comment by gi0baro** [comment]
Hi @toplinuxsir, unfortunately the test client (#40) is planned for the next release.
0.6 should come by the end of the year, with this revision testing facilities will be implemented and documented.

**Comment by toplinuxsir** [comment]
Thanks for your work!

Giovanni Barillari <notifications@github.com>于2015年12月4日 周五下午6:48写道：

**Comment by gi0baro** [comment]
@toplinuxsir I've just pushed on master a first implementation of the testing suite with https://github.com/gi0baro/weppy/commit/10b174a8a512cc8e39cb1b8a0302e17658470d99

I have to write the documentation, but if you look at https://github.com/gi0baro/weppy/blob/master/examples/bloggy/tests.py it might give you an idea on how it works (pytest based tests, but you can use unittest2 or whatever).
Feedbacks are always welcome :)

**Comment by gi0baro** [comment]
I'm closing this since 0.6 is released. Check out the documentation for the tests: http://weppy.org/docs/0.6/testing
