### ISSUE TITLE
'App' object has no attribute 'route' on bloggy example

### ISSUE THREAD

**Issue by pbreit** [gi0baro/weppy#78]
I just tried weepy for the first time (pip install on a virtualenv). I put in all the code for the bloggy example and am getting 'App' object has no attribute 'route'

I tried switching back to "expose" which avoided the errors but the app just hangs in my browser. How do I tell what version of weepy I'm on? I see expose was deprecated for route recently.

Is there a Google Group or anything for discussion or is this the best place for issues?

**Comment by gi0baro** [comment]
Hi @pbreit,
to know which version of weppy you have you can just open up a python shell and do:

```python
Python 2.7.8 (default, Nov  6 2014, 14:53:57)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import weppy
>>> weppy.__version__
'0.5.4'
```

The issue you have comes from the fact you installed the latest release available and cloned the code from the current *master*, which will be the next revision. So, generally speaking, you should follow the [docs](http://weppy.org/docs) which will always point out to the latest release and refers to the [release branch](https://github.com/gi0baro/weppy/tree/release) here on github when using the latest release.

Just to clarify, `app.route` will be available in 0.6 where `app.expose` will be deprecated. In weppy 0.7 `app.expose` will be totally removed.

There's a [google group](https://groups.google.com/forum/#!forum/weppy-talk) available, check it out.

In the meantime, happy coding! Will be awesome to have your feedbacks on weppy.
