### ISSUE TITLE
Add year of first release to copyright notice

### ISSUE THREAD

**Issue by GiantCrocodile** [gi0baro/weppy#79]
I think 2014 should be added to copyright notice to show how old this project is and to show how proud all of us are to see it grow within past years. Then we can easily celebrate 10 years of development soon. Thanks to copyright info @gi0baro ;)!

**Comment by gi0baro** [comment]
@GiantCrocodile seems legit. Are you suggesting to update it only in the LICENSE file or in every file header?

**Comment by GiantCrocodile** [comment]
I think it should be mentioned in any file to show also that there has been a previous copyright like if name conflicts occur for past dates.
