### ISSUE TITLE
Misspelling on weppy.org

### ISSUE THREAD

**Issue by lethargilistic** [gi0baro/weppy#89]
**Really** minor and I'd just fix it myself if I could PR weppy.org, but that doesn't seem possible.

In the "Aggregation made easy" section, "Ned to count...?" should be "Need to count...?"

**Comment by gi0baro** [comment]
@lethargilistic Thank you for the catch! I will update the website quite soon.

Also, I will publish the source code of the website in a separate repository here on github in the next weeks so that you can make PRs for that :)

**Comment by lethargilistic** [comment]
Additionally, in the Docs landing page "reccomend" should be "recommend."

**Comment by lethargilistic** [comment]
@gi0baro Great. This project looks really cool. :)

**Comment by gi0baro** [comment]
@lethargilistic weppy.org is now updated with your suggested changes.
