### ISSUE TITLE
Little speeling error on your homepage

### ISSUE THREAD

**Issue by daftspunk** [gi0baro/weppy#92]
Good day Python friends!

"Unlike many frameworks, weppy won't propose you a new templating language, with a different syntax and logic: you shouldn't **loose** time for that.

See **in bold** should be `lose`

Page ref: http://weppy.org/
Section ref: A CLEAN TEMPLATING ENGINE

<3

**Comment by gi0baro** [comment]
@daftspunk Thanks man. Will fix this asap. :)

**Comment by collingreen** [comment]
Came here to post this :)

**Comment by gi0baro** [comment]
Fixed, thank you all :)
