### ISSUE TITLE
Support for WYSIWYG Editor in weppy forms

### ISSUE THREAD

**Issue by vegax87** [gi0baro/weppy#93]
I would like to integrate a specific textarea in a form with a modern WYSIWYG Editor like Summernote.
Does it require a new extension?

**Comment by gi0baro** [comment]
Hi @vegax87,
I think you can better go with a custom widget. If the form comes from a model, you can use the `form_widgets` attribute:

```python
form_widgets = {
    "textfield": wys_widget
}
```

where `wys_widget` is just a method that renders the html, you can use the `tag` weppy html helper (I haven't documented it yet, I'm sorry about that):

```python
from weppy import tag

def wys_widget(field, value):
    return tag.textarea(
        value if value else '',
        _id="summernote",
        _name=field.name
    )
```
I'm not used to Summernote, but then should be enough to add the javascript to the page:

```javascript
$(document).ready(function() {
  $('#summernote').summernote();
});
```

Hope I explained you the idea..

**Comment by laozhu** [comment]
It's very nice method to add WYSIWYG editor support.
Very helpful, Thanks.
